name: Automate Book Content Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moviepy imageio imageio-ffmpeg
        pip install -r requirements.txt || true

    - name: Debug Python env (for sanity check)
      run: |
        which python
        python --version
        pip list

    - name: Run automation script
      run: python generate_all.py

